services:
  - type: web
    name: sentinelx-website-backend
    env: docker
    dockerfilePath: apps/website/backend/Dockerfile
    dockerContext: apps/website/backend
    region: singapore
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_HOST
        value: ep-wispy-pond-b3kdnoy1-pooler.c-4.ap-southeast-1.aws.neon.tech
      - key: DB_NAME
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
